const USERS_TABLE_NAME = "Users";
const PASSWORDS_TABLE_NAME = "Passwords";
const EMAILS_TABLE_NAME = "Emails";

// users
const INSERT_USER_QUERY = `INSERT INTO ${USERS_TABLE_NAME} (uID, username) VALUES (?, ?)`;
const GET_USER_QUERY = `SELECT username FROM ${USERS_TABLE_NAME} WHERE uID = ?`;
const DELETE_USER_QUERY = `DELETE FROM ${USERS_TABLE_NAME} WHERE uID = ?`;

// passwords
const INSERT_PASSWORD_QUERY = `INSERT INTO ${PASSWORDS_TABLE_NAME} (uID, password) VALUES (?, ?)}`
const GET_PASSWORD_QUERY = `SELECT password FROM ${PASSWORDS_TABLE_NAME} WHERE uID = ?`;
const UPDATE_PASSWORD_QUERY = `UPDATE ${PASSWORDS_TABLE_NAME} SET email = ? WHERE uID = ?`;
const  DELETE_PASSWORD_QUERY = `DELETE FROM ${PASSWORDS_TABLE_NAME} WHERE uID = ?`;

// emails
const INSERT_EMAIL_QUERY = `INSERT INTO ${EMAILS_TABLE_NAME} (uID, email) VALUES (?, ?)`;
const  GET_EMAIL_QUERY = `SELECT email FROM ${EMAILS_TABLE_NAME} WHERE uID = ?`;
const  UPDATE_EMAIL_QUERY = `UPDATE ${EMAILS_TABLE_NAME} SET email = ? WHERE uID = ?`;
const  DELETE_EMAIL_QUERY =`DELETE FROM ${EMAILS_TABLE_NAME} WHERE uID = ?`;

module.exports = {
    INSERT_USER_QUERY,
    GET_USER_QUERY,
    DELETE_USER_QUERY,
    INSERT_PASSWORD_QUERY,
    GET_PASSWORD_QUERY,
    UPDATE_PASSWORD_QUERY,
    INSERT_EMAIL_QUERY,
    GET_EMAIL_QUERY,
    UPDATE_EMAIL_QUERY,
    DELETE_EMAIL_QUERY
}

