const ALL_OK_CODE = 200;
const MISSING_PARAMETERS_CODE = 400;
const EMAIL_REGISTERED_CODE = 401;
const EMAIL_DOES_NOT_EXIST_CODE = 401;
const INVALID_PASSWORD_CODE = 402;
const USER_NOT_FOUND_CODE = 403;
const INVALID_USER_CREDENTIALS_CODE = 405;
const INVALID_TOKEN_CODE = 406;

const SERVER_ERROR_CODE = 500;

module.exports = {
    ALL_OK_CODE,
    MISSING_PARAMETERS_CODE,
    EMAIL_REGISTERED_CODE,
    EMAIL_DOES_NOT_EXIST_CODE,
    INVALID_PASSWORD_CODE,
    USER_NOT_FOUND_CODE,
    INVALID_USER_CREDENTIALS_CODE,
    INVALID_TOKEN_CODE,
    SERVER_ERROR_CODE,
}